// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace staffstudent.Entities
{
    public partial class StaffmanagementContext : DbContext
    {
        public StaffmanagementContext()
        {
        }

        public StaffmanagementContext(DbContextOptions<StaffmanagementContext> options)
            : base(options)
        {
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Staffmanagement");
            }
        }
        public virtual DbSet<StudentInformation> StudentInformation { get; set; }
        public virtual DbSet<StudentMark> StudentMark { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<StudentInformation>(entity =>
            {
                entity.Property(e => e.StudentRollNo).ValueGeneratedNever();

                entity.Property(e => e.CreatedTimeStamp).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Email).IsUnicode(false);

                entity.Property(e => e.FatherFirstName).IsUnicode(false);

                entity.Property(e => e.FatherLastName).IsUnicode(false);

                entity.Property(e => e.FatherSOccupation).IsUnicode(false);

                entity.Property(e => e.Gender).IsUnicode(false);

                entity.Property(e => e.MotherFirstName).IsUnicode(false);

                entity.Property(e => e.MotherLastName).IsUnicode(false);

                entity.Property(e => e.Password).IsUnicode(false);

                entity.Property(e => e.StudentFirstName).IsUnicode(false);

                entity.Property(e => e.StudentLastName).IsUnicode(false);

                entity.Property(e => e.UpdatedTimeStamp).HasDefaultValueSql("(getdate())");
            });

            modelBuilder.Entity<StudentMark>(entity =>
            {
                entity.Property(e => e.StudentRollNo).ValueGeneratedNever();

                entity.Property(e => e.CreatedTimeStamp).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Subject).IsUnicode(false);

                entity.Property(e => e.UpdatedTimeStamp).HasDefaultValueSql("(getdate())");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}