// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace staffstudent.Entities
{
    [Table("Student_Information")]
    public partial class StudentInformation
    {
        [Key]
        [Column("Student_Roll_No")]
        public int StudentRollNo { get; set; }
        [Required]
        [Column("Student_First_name")]
        [StringLength(40)]
        public string StudentFirstName { get; set; }
        [Required]
        [Column("Student_Last_Name")]
        [StringLength(40)]
        public string StudentLastName { get; set; }
        [Required]
        [StringLength(6)]
        public string Gender { get; set; }
        [Column("DOB", TypeName = "date")]
        public DateTime? Dob { get; set; }
        [Required]
        [Column("Father_First_name")]
        [StringLength(40)]
        public string FatherFirstName { get; set; }
        [Required]
        [Column("Father_Last_name")]
        [StringLength(40)]
        public string FatherLastName { get; set; }
        [Required]
        [Column("Mother_First_name")]
        [StringLength(40)]
        public string MotherFirstName { get; set; }
        [Required]
        [Column("Mother_Last_name")]
        [StringLength(40)]
        public string MotherLastName { get; set; }
        [Required]
        [StringLength(60)]
        public string Email { get; set; }
        [Column("Student_Contact_no")]
        public long StudentContactNo { get; set; }
        [Column("Father's_Contact_no")]
        public long FatherSContactNo { get; set; }
        [Required]
        [Column("Father's_occupation")]
        [StringLength(30)]
        public string FatherSOccupation { get; set; }
        [Column("Is_deleted")]
        public bool IsDeleted { get; set; }
        [Column("Created_time_stamp", TypeName = "datetime")]
        public DateTime CreatedTimeStamp { get; set; }
        [Column("Updated_time_stamp", TypeName = "datetime")]
        public DateTime UpdatedTimeStamp { get; set; }
        [Required]
        [StringLength(10)]
        public string Password { get; set; }
    }
}