//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mail_scheduler_service.DLL.Mail_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMark
    {
        public int Student_Roll_no { get; set; }
        public int Tamil { get; set; }
        public int English { get; set; }
        public int Science { get; set; }
        public int Maths { get; set; }
        public int Total { get; set; }
        public double Average { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> Scheduled_time { get; set; }
        public bool Is_deleted { get; set; }
        public System.DateTime Created_time_stamp { get; set; }
        public System.DateTime Updated_time_stamp { get; set; }
    }
}
