//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mail_scheduler_service.DLL.Mail_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Information
    {
        public int Student_Roll_No { get; set; }
        public string Student_First_name { get; set; }
        public string Student_Last_Name { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Father_First_name { get; set; }
        public string Father_Last_name { get; set; }
        public string Mother_First_name { get; set; }
        public string Mother_Last_name { get; set; }
        public string Email { get; set; }
        public long Student_Contact_no { get; set; }
        public long Father_s_Contact_no { get; set; }
        public string Father_s_occupation { get; set; }
        public bool Is_deleted { get; set; }
        public System.DateTime Created_time_stamp { get; set; }
        public System.DateTime Updated_time_stamp { get; set; }
        public string Password { get; set; }
    }
}
